name: Selenium Test Execution and Reporting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-test:
    name: Run Selenium Tests on Chrome and Firefox
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Cache Python dependencies
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install Chrome, Firefox, ChromeDriver, and GeckoDriver
      - name: Set up Chrome, Firefox, ChromeDriver, and GeckoDriver
        run: |
          sudo apt-get update
          # Install Chrome
          sudo apt-get install -y google-chrome-stable
          wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Install Firefox
          sudo apt-get install -y firefox
          wget -N https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
        
        env:
          CHROME_BIN: /usr/bin/google-chrome
          CHROME_DRIVER: /usr/local/bin/chromedriver
          FIREFOX_BIN: /usr/bin/firefox
          GECKO_DRIVER: /usr/local/bin/geckodriver

      # Step 5: Install Python dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 6: Run the tests on Firefox
      - name: Run Selenium Tests on Firefox
        run: |
          cd test
          mkdir -p reports
          pytest testLogin.py --browser=firefox --html=reports/Firefox-report.html --maxfail=2
        continue-on-error: false

      # Step 7: Run the tests on Chrome
      - name: Run Selenium Tests on Chrome
        run: |
          cd test
          mkdir -p reports
          pytest testLogin.py --browser=chrome --html=reports/Chrome-report.html --maxfail=2
        continue-on-error: true

      # Step 8: Upload Firefox test reports
      - name: Upload Firefox Test Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-firefox-test-report
          path: test/reports/Firefox-report.html

      # Step 9: Upload Chrome test reports
      - name: Upload Chrome Test Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-chrome-test-report
          path: test/reports/Chrome-report.html
